#!/usr/bin/env python3
#
# Copyright (c) 2026 Guy's and St Thomas' NHS Foundation Trust & King's College London
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

"""FLIP Deployment Status Checker.

This script verifies that the AWS deployment is functioning correctly.

PREREQUISITES:
  - terraform (to read outputs from terraform.tfstate)
  - aws CLI (configured with appropriate credentials)
  - AWS SSM Session Manager plugin (for SSH-over-SSM connectivity)
    - SSH config aliases 'flip' and 'flip-trust' (generated by update_ssm_ssh_config.py)

WHAT IT CHECKS:
  ✓ AWS Resources (EC2 instances, RDS, S3, Secrets Manager)
  ✓ Network Connectivity (SSH via SSM, HTTP) for Central Hub bastion & Trust EC2
  ✓ Application Endpoints (UI + flip-api via ALB/CloudFront)
  ✓ ECS services (flip-api, fl-api-net-N, fl-server-net-N) — desired vs running,
    deployment rollout state, ALB/NLB target group health
  ✓ Trust Endpoints (Trust API, Imaging API, Data Access API on Trust EC2 — /health)
  ✓ Trust Services (FL clients, OMOP database, Trust APIs) via Docker on Trust EC2
  ✓ System Resources (disk, memory) on both EC2 instances
  ✓ CloudWatch Logs (ECS log groups for flip-api / fl-server / fl-api,
    EC2 log groups for the SSM bastion + Trust EC2)
  ✓ Recent error scans against CloudWatch (no docker exec required)

EXIT CODES:
  0 - All checks passed (warnings are acceptable)
  1 - One or more checks failed
"""

import base64
import json
import os
import platform
import ssl
import subprocess
import sys
import urllib.parse
import urllib.request
from dataclasses import dataclass
from pathlib import Path

import click

flip_application_bucket_names = [
    ("model file uploads", os.getenv("FLIP_MODEL_FILES_UPLOADS_BUCKET_NAME")),
    ("FL results", os.getenv("FLIP_FL_RESULTS_BUCKET_NAME")),
    ("app bundles", os.getenv("FLIP_APP_BUNDLES_BUCKET_NAME")),
]


# Color codes for terminal output
class Colors:
    """ANSI color codes for terminal output."""

    RED = "\033[0;31m"
    GREEN = "\033[0;32m"
    YELLOW = "\033[1;33m"
    BLUE = "\033[0;34m"
    NC = "\033[0m"  # No Color


@dataclass
class StatusCounters:
    """Track check results."""

    passed: int = 0
    failed: int = 0
    warnings: int = 0

    @property
    def total(self) -> int:
        """Get total checks."""
        return self.passed + self.failed + self.warnings


# Global counters
counters = StatusCounters()


def print_status(status: str, message: str) -> None:
    """Print a status message with color coding.

    Args:
        status: Status type (PASS, FAIL, INFO, WARN)
        message: Message to display
    """
    global counters

    symbols = {
        "PASS": f"{Colors.GREEN}✓ PASS{Colors.NC}",
        "FAIL": f"{Colors.RED}✗ FAIL{Colors.NC}",
        "WARN": f"{Colors.YELLOW}⚠ WARN{Colors.NC}",
        "INFO": f"{Colors.BLUE}ℹ INFO{Colors.NC}",
    }

    symbol = symbols.get(status, "")
    click.echo(f"{symbol} - {message}")

    if status == "PASS":
        counters.passed += 1
    elif status == "FAIL":
        counters.failed += 1
    elif status == "WARN":
        counters.warnings += 1


def print_section(title: str) -> None:
    """Print a section header.

    Args:
        title: Section title
    """
    click.echo()
    click.echo(f"{Colors.BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━{Colors.NC}")
    click.echo(f"{Colors.BLUE}{title}{Colors.NC}")
    click.echo(f"{Colors.BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━{Colors.NC}")


def check_command(command: str) -> bool:
    """Check if a command is available.

    Args:
        command: Command name to check

    Returns:
        True if command exists, False otherwise
    """
    try:
        subprocess.run(
            ["which", command] if platform.system() != "Windows" else ["where", command],
            capture_output=True,
            check=True,
            timeout=5,
        )
        return True
    except (subprocess.CalledProcessError, FileNotFoundError, subprocess.TimeoutExpired):
        return False


def get_terraform_output(output_name: str) -> str | None:
    """Get a specific output value from Terraform.

    Args:
        output_name: Name of the Terraform output variable

    Returns:
        The output value or None if not found
    """
    try:
        result = subprocess.run(
            ["terraform", "output", "-raw", output_name],
            capture_output=True,
            text=True,
            check=True,
            timeout=10,
        )
        output = result.stdout.strip()
        if output and output != "null":
            return output
        return None
    except (subprocess.CalledProcessError, subprocess.TimeoutExpired):
        return None


def run_aws_command(args: list[str]) -> tuple[bool, str]:
    """Run an AWS CLI command.

    Args:
        args: AWS CLI arguments

    Returns:
        Tuple of (success, output)
    """
    try:
        result = subprocess.run(
            ["aws"] + args,
            capture_output=True,
            text=True,
            check=True,
            timeout=30,
        )
        return True, result.stdout.strip()
    except (subprocess.CalledProcessError, subprocess.TimeoutExpired) as e:
        return False, str(e)


def format_ssm_ping_status(success: bool, ping_status: str) -> str:
    """Format an SSM ping-status query result for operator output.

    Args:
        success: Whether the AWS CLI command completed successfully.
        ping_status: Stripped stdout from the command, or its error description.

    Returns:
        A clear status description for the deployment report.
    """
    if not success:
        return f"query failed: {ping_status or 'unknown error'}"
    if ping_status in {"", "None"}:
        return "not registered"
    return ping_status


def run_ssh_command(ssh_key: str, host: str, command: str, timeout: int = 10) -> tuple[bool, str]:
    """Run a command via SSH.

    Args:
        ssh_key (str): Path to SSH key, or empty string to use SSH config defaults
        host (str): Host address (user@ip) or SSH config alias (e.g. 'flip')
        command (str): Command to run
        timeout (int): Command timeout in seconds

    Returns:
        tuple[bool, str]: (success, output)
    """
    try:
        cmd = ["ssh"]
        if ssh_key:
            cmd += ["-i", ssh_key]
        cmd += [
            "-o",
            "StrictHostKeyChecking=accept-new",
            "-o",
            f"ConnectTimeout={timeout}",
            host,
            command,
        ]
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            check=True,
            timeout=timeout + 5,
        )
        return True, result.stdout.strip()
    except (subprocess.CalledProcessError, subprocess.TimeoutExpired) as e:
        return False, str(e)


def run_remote_python(host: str, container: str, source: str, timeout: int = 25) -> tuple[bool, str]:
    """Execute a Python snippet inside a remote Docker container via base64 encoding.

    Avoids shell quoting issues by encoding the snippet in base64, piping it
    through ``docker exec -i``, and letting Python eval the decoded content.
    """
    encoded = base64.b64encode(source.encode()).decode()
    cmd = f"echo {encoded} | base64 -d | docker exec -i {container} python3"
    return run_ssh_command("", host, cmd, timeout=timeout)


def check_http_endpoint(
    url: str,
    name: str,
    expected_status: int | list[int] = 200,
    cafile: str | None = None,
) -> bool:
    """Check HTTP endpoint availability.

    Args:
        url: URL to check
        name: Endpoint name for logging
        expected_status: Expected HTTP status code(s). Can be a single int or list of ints.
        cafile: Optional path to a custom CA bundle for HTTPS verification.

    Returns:
        True if endpoint is accessible, False otherwise
    """
    print_status("INFO", f"Checking {name} at {url}...")

    # Validate URL scheme — only http and https are permitted
    _scheme = urllib.parse.urlparse(url).scheme
    if _scheme not in ("http", "https"):
        print_status("FAIL", f"{name}: unsupported URL scheme '{_scheme}' (only http/https allowed)")
        return False

    # Convert single int to list for uniform handling
    valid_statuses = [expected_status] if isinstance(expected_status, int) else expected_status

    # Build SSL context: use provided CA bundle, or system defaults for HTTPS URLs.
    ssl_ctx: ssl.SSLContext | None = None
    if _scheme == "https":
        if cafile and Path(cafile).exists():
            ssl_ctx = ssl.create_default_context(cafile=cafile)
        else:
            ssl_ctx = ssl.create_default_context()
        ssl_ctx.minimum_version = ssl.TLSVersion.TLSv1_2

    try:
        req = urllib.request.Request(url, method="GET")
        with urllib.request.urlopen(req, timeout=10, context=ssl_ctx) as response:
            if response.status in valid_statuses:
                print_status("PASS", f"{name} is responding (HTTP {response.status})")
                return True
            else:
                print_status(
                    "FAIL",
                    (f"{name} returned HTTP {response.status} (expected {valid_statuses})"),
                )
                return False
    except urllib.error.HTTPError as e:
        # Handle HTTP errors (like 401) that still indicate the service is responding
        if e.code in valid_statuses:
            print_status("PASS", f"{name} is responding (HTTP {e.code})")
            return True
        else:
            print_status("FAIL", f"{name} returned HTTP {e.code} (expected {valid_statuses})")
            return False
    except Exception as e:
        print_status("FAIL", f"{name} not responding: {e}")
        return False


def check_endpoint_over_ssh(
    host: str,
    endpoint: str,
    expected_status: int = 200,
    verify_ssl: bool = True,
) -> bool:
    """Check an HTTP/HTTPS endpoint from a remote host via SSH.

    Args:
        host: Host alias (from ~/.ssh/config) or user@ip
        endpoint: URL to check
        expected_status: Expected HTTP status code
        verify_ssl: When False, passes -k to curl to skip certificate validation

    Returns:
        True if endpoint is accessible, False otherwise
    """
    skip_flag = "" if verify_ssl else "-k "
    command = f"curl -s {skip_flag}-o /dev/null -w '%{{http_code}}' {endpoint}"
    print_status(status="INFO", message=f"Checking endpoint {endpoint} from {host} via SSH...")
    success, output = run_ssh_command(ssh_key="", host=host, command=command)
    if success and output == str(expected_status):
        print_status("PASS", f"{endpoint} is accessible from {host}")
        return True
    else:
        print_status("FAIL", f"{endpoint} is not accessible from {host}: {output}")
        return False


def check_endpoint_rejects_insecure_ssh(
    host: str,
    endpoint: str,
) -> bool:
    """Verify that a secure endpoint rejects insecure HTTP requests via SSH.

    This is a SECURITY CHECK: ensures that an HTTPS endpoint does not respond
    to HTTP requests (i.e., redirects or rejects, but doesn't serve with 200).

    Args:
        host: Host alias (from ~/.ssh/config) or user@ip
        endpoint: HTTPS URL to check

    Returns:
        True if insecure request is properly rejected, False if it somehow succeeds
    """
    insecure_endpoint = endpoint.replace("https://", "http://")
    command = f"curl -s -o /dev/null -w '%{{http_code}}' {insecure_endpoint}"
    print_status(
        status="INFO",
        message=f"SECURITY: Verifying {insecure_endpoint} rejects insecure request from {host}...",
    )
    success, output = run_ssh_command(ssh_key="", host=host, command=command)

    if success and output == "200":
        print_status(
            "FAIL",
            f"{insecure_endpoint} CRITICALLY responded with HTTP 200 from {host}. "
            f"HTTPS-only endpoints must reject HTTP requests.",
        )
        return False
    else:
        print_status(
            "PASS",
            f"{insecure_endpoint} properly rejected from {host}",
        )
        return True


def ping_host(host: str) -> bool:
    """Ping a host to check connectivity.

    Args:
        host: Host address to ping

    Returns:
        True if host is reachable, False otherwise
    """
    param = "-n" if platform.system() == "Windows" else "-c"
    try:
        subprocess.run(
            ["ping", param, "1", "-W", "2", host],
            capture_output=True,
            check=True,
            timeout=5,
        )
        return True
    except (subprocess.CalledProcessError, subprocess.TimeoutExpired):
        return False


# ── Deep Smoke Tests (added from EC2-to-ECS migration lessons) ────


def check_ecs_cluster() -> None:
    """Verify the ECS cluster exists and is ACTIVE.

    Detects: missing cluster, cluster in DEPROVISIONING state, or no cluster
    defined at all (EC2-only deployment with no ECS migration in progress).
    """
    print_status("INFO", "Checking ECS cluster...")
    cluster_names = []
    success, output = run_aws_command([
        "ecs",
        "list-clusters",
        "--query",
        "clusterArns",
        "--output",
        "json",
    ])
    if success and output:
        try:
            cluster_names = json.loads(output)
        except json.JSONDecodeError:
            pass

    if not cluster_names:
        print_status("INFO", "No ECS clusters found (EC2-only deployment)")
        return

    success2, output2 = run_aws_command([
        "ecs",
        "describe-clusters",
        "--clusters",
        *cluster_names,
        "--query",
        "clusters[0].{name:clusterName,status:status,services:activeServicesCount}",
        "--output",
        "json",
    ])
    if success2 and output2:
        try:
            data = json.loads(output2)
            name = data.get("name", "?")
            status = data.get("status", "?")
            svc_count = data.get("services", 0)
            if status == "ACTIVE":
                print_status("PASS", f"ECS cluster '{name}' is ACTIVE ({svc_count} services)")
            else:
                print_status("WARN", f"ECS cluster '{name}' status: {status} ({svc_count} services)")
        except (json.JSONDecodeError, KeyError):
            print_status("WARN", f"Could not parse ECS cluster status: {output2[:200]}")
    else:
        print_status("WARN", "Could not describe ECS clusters")


def check_vpc_endpoints() -> None:
    """Verify configured AWS VPC interface endpoints are AVAILABLE.

    Detects broken endpoints that would block ECS Fargate tasks from reading
    parameters or secrets, or from writing logs.
    """
    print_status("INFO", "Checking VPC endpoints...")
    success, output = run_aws_command([
        "ec2",
        "describe-vpc-endpoints",
        "--filters",
        "Name=vpc-endpoint-type,Values=Interface",
        "--query",
        "VpcEndpoints[].{Name:ServiceName,State:State}",
        "--output",
        "json",
    ])
    if not success or not output:
        print_status("INFO", "Could not query VPC endpoints (may need ec2:DescribeVpcEndpoints)")
        return

    try:
        endpoints = json.loads(output)
    except json.JSONDecodeError:
        print_status("WARN", "Could not parse VPC endpoint data")
        return

    for ep in endpoints:
        name = ep.get("Name", "")
        state = ep.get("State", "?")
        if name.startswith("com.amazonaws."):
            if state == "available":
                print_status("PASS", f"VPC endpoint {name.split('.')[-1]} is {state}")
            else:
                print_status("WARN", f"VPC endpoint {name.split('.')[-1]} is {state}")


def check_trust_pipeline() -> None:
    """Trust task pipeline health used to query the DB via ``docker exec flip-api``.

    flip-api now runs on ECS Fargate with ``enableExecuteCommand=false`` so the
    in-container DB query is no longer reachable from the smoke test. Checking
    the pipeline state still has value, but it requires a bastion container
    that holds DB credentials and the right SG egress to RDS — that is not yet
    in place. Surface the gap as INFO so operators know the check exists in
    intent but not in implementation, and skip cleanly.
    """
    print_status(
        "INFO",
        "Trust task pipeline DB check skipped — requires ECS Exec or a bastion task on the ECS network "
        "(both unavailable). Run the ad-hoc query in TROUBLESHOOTING.md §5 from a developer workstation.",
    )


def check_xnat_health() -> None:
    """Verify XNAT is serving its API (not a setup page)."""
    print_status("INFO", "Checking XNAT API health (not setup page)...")

    py = """\
import os, requests
r = requests.get(
    "http://xnat-web:8080/data/projects",
    auth=(os.environ.get("XNAT_SERVICE_USER", "flipServiceAccount"),
          os.environ.get("XNAT_SERVICE_PASSWORD", "")),
    timeout=10,
)
print(r.status_code, r.headers.get("content-type", "").split(";")[0])
"""
    success, output = run_remote_python("flip-trust", "trust1-imaging-api-1", py, timeout=25)

    if not success or "Traceback" in output:
        print_status("INFO", "Could not check XNAT (SSH unavailable)")
        return

    parts = output.strip().split()
    if not parts:
        print_status("WARN", "XNAT returned empty response")
        return

    try:
        code = int(parts[0])
        ctype = parts[1] if len(parts) > 1 else ""
    except (ValueError, IndexError):
        print_status("WARN", f"Could not parse XNAT response: {output[:100]}")
        return

    if code == 200 and "html" not in ctype.lower():
        print_status("PASS", f"XNAT API responding (HTTP {code})")
    elif code == 200 and "html" in ctype.lower():
        print_status("FAIL", "XNAT returned HTML (setup page?) — restart XNAT web container")
    elif code == 401:
        print_status("FAIL", "XNAT API returned 401 — check XNAT_SERVICE_USER/PASSWORD in .env.stag")
    else:
        print_status("WARN", f"XNAT API returned HTTP {code}")


def check_reimport_status() -> None:
    """Stuck-reimport check used the same ``docker exec flip-api`` path that
    the trust pipeline check did. Same blocker post-ECS — surface the gap and
    skip rather than silently passing.
    """
    print_status(
        "INFO",
        "Reimport-stall check skipped — same ECS Exec dependency as the trust pipeline check. "
        "Verify manually via the SQL in TROUBLESHOOTING.md §5 if you suspect a stall.",
    )


def _filter_log_events(log_group: str, pattern: str, minutes: int = 60) -> tuple[bool, list[str]]:
    """Return matching CloudWatch log messages from the last N minutes.

    Args:
        log_group: CloudWatch log group name (e.g. ``/ecs/flip-api``).
        pattern: CloudWatch Logs filter pattern (terms separated by spaces are
            ANDed; quoted phrases match literally; prefix with ``?`` for OR).
        minutes: Lookback window in minutes.

    Returns:
        Tuple of (success, list of message strings). On API/parse failure,
        success is False and the list is empty.
    """
    import time

    start_time_ms = int((time.time() - minutes * 60) * 1000)
    success, output = run_aws_command([
        "logs",
        "filter-log-events",
        "--log-group-name",
        log_group,
        "--start-time",
        str(start_time_ms),
        "--filter-pattern",
        pattern,
        "--query",
        "events[].message",
        "--output",
        "json",
    ])
    if not success or not output:
        return False, []
    try:
        return True, json.loads(output)
    except json.JSONDecodeError:
        return False, []


def check_fl_server_clients(net_numbers: list[int]) -> None:
    """Verify the ECS fl-server log shows trust FL clients connected.

    Reads ``/ecs/fl-server-net-N`` CloudWatch logs (last 24h) for the
    ``Re-activate the client`` line NVFLARE emits when a registered client
    reconnects. Falls back to ``Client: New`` for first-time registrations.
    """
    print_status("INFO", "Checking FL server clients (CloudWatch /ecs/fl-server-net-N)...")
    for net in net_numbers:
        log_group = f"/ecs/fl-server-net-{net}"
        ok, events = _filter_log_events(log_group, '"Re-activate the client"', minutes=24 * 60)
        if ok and events:
            print_status("PASS", f"fl-server-net-{net} has re-activated clients ({len(events)} events in 24h)")
            continue
        ok2, events2 = _filter_log_events(log_group, '"Client: New"', minutes=24 * 60)
        if ok2 and events2:
            print_status("PASS", f"fl-server-net-{net} has new client registrations ({len(events2)} events in 24h)")
        elif ok or ok2:
            print_status(
                "WARN",
                f"fl-server-net-{net} has no connected clients in last 24h — "
                "check NLB target group health and trust fl-client logs",
            )
        else:
            print_status("INFO", f"Could not query CloudWatch log group {log_group}")


def check_container_errors(net_numbers: list[int]) -> None:
    """Scan ECS log groups for recent errors.

    Pulls from ``/ecs/flip-api``, ``/ecs/fl-api-net-N``, and
    ``/ecs/fl-server-net-N`` over the last 5 minutes and counts events
    matching ERROR / Traceback / Exception / DNS resolution failures.
    """
    print_status("INFO", "Scanning ECS log groups for recent errors (last 5 min)...")
    pattern = '?ERROR ?Traceback ?Exception ?"Name or service not known"'

    log_groups = ["/ecs/flip-api"]
    for net in net_numbers:
        log_groups += [f"/ecs/fl-api-net-{net}", f"/ecs/fl-server-net-{net}"]

    for log_group in log_groups:
        ok, events = _filter_log_events(log_group, pattern, minutes=5)
        if not ok:
            print_status("INFO", f"Could not query CloudWatch log group {log_group}")
            continue
        count = len(events)
        if count == 0:
            print_status("PASS", f"No errors in {log_group} (last 5 min)")
        elif count <= 5:
            print_status("WARN", f"{count} error(s) in {log_group} (last 5 min) — review if recurring")
        else:
            print_status("FAIL", f"{count} errors in {log_group} (last 5 min) — investigate immediately")


def check_net_endpoints_consistency() -> None:
    """NET_ENDPOINTS env-vs-DB consistency.

    Used to query the DB via ``docker exec flip-api`` on EC2. Same blocker as
    ``check_trust_pipeline``. The env-vs-DB cache divergence the original
    check guarded against is also less load-bearing now that NET_ENDPOINTS
    points at Cloud Map FQDNs (resolution is done by the VPC resolver, not
    cached anywhere).
    """
    print_status(
        "INFO",
        "NET_ENDPOINTS env-vs-DB check skipped — required ``docker exec flip-api`` and is now "
        "obsolete with Cloud Map (FQDNs resolve via the VPC resolver, not the fl_nets cache).",
    )


def check_mfa_config() -> None:
    """ENFORCE_MFA configuration on flip-api.

    Read directly from the ECS task definition ``environment`` block — this
    is the source of truth for what the running container sees. The Settings
    default is ``true``; absence of an explicit ``false`` is a pass.
    """
    print_status("INFO", "Checking ENFORCE_MFA on flip-api ECS task definition...")
    success, output = run_aws_command([
        "ecs",
        "describe-services",
        "--cluster",
        "flip-cluster",
        "--services",
        "flip-api",
        "--query",
        "services[0].taskDefinition",
        "--output",
        "text",
    ])
    if not success or not output:
        print_status("INFO", "Could not read flip-api task definition")
        return

    success2, td = run_aws_command([
        "ecs",
        "describe-task-definition",
        "--task-definition",
        output.strip(),
        "--query",
        "taskDefinition.containerDefinitions[0].environment",
        "--output",
        "json",
    ])
    if not success2 or not td:
        print_status("INFO", "Could not read flip-api task definition environment")
        return

    try:
        env = {e["name"]: e["value"] for e in json.loads(td)}
    except (json.JSONDecodeError, KeyError, TypeError):
        print_status("WARN", "Could not parse flip-api task definition environment")
        return

    value = env.get("ENFORCE_MFA", "<unset — Settings default true>").lower()
    if value == "false":
        print_status("WARN", "ENFORCE_MFA=false on flip-api task — TOTP enforcement disabled")
    elif value == "true" or "default" in value:
        print_status("PASS", f"ENFORCE_MFA={value} — TOTP enforcement enabled")
    else:
        print_status("WARN", f"Unexpected ENFORCE_MFA value on flip-api task: {value}")


# ── ECS-specific deep checks ──────────────────────────────────────


def check_ecs_services_running(net_numbers: list[int]) -> None:
    """Verify each ECS service has runningCount == desiredCount and no failed deployment.

    A service is considered healthy when:
      • status == ACTIVE
      • runningCount == desiredCount (and desiredCount > 0)
      • the latest deployment rolloutState == COMPLETED (or the service hasn't
        deployed yet but is steady)

    Mid-rollout transitions (IN_PROGRESS) downgrade to WARN — useful for
    distinguishing "currently rolling" from "stuck rolling".
    """
    print_status("INFO", "Checking ECS service rollout state...")
    services = ["flip-api"] + [f"fl-api-net-{n}" for n in net_numbers] + [f"fl-server-net-{n}" for n in net_numbers]
    success, output = run_aws_command([
        "ecs",
        "describe-services",
        "--cluster",
        "flip-cluster",
        "--services",
        *services,
        "--query",
        (
            "services[].{name:serviceName,status:status,desired:desiredCount,"
            "running:runningCount,"
            "deployments:deployments[?status==`PRIMARY`].rolloutState | [0]}"
        ),
        "--output",
        "json",
    ])
    if not success or not output:
        print_status("FAIL", "Could not describe ECS services")
        return

    try:
        data = json.loads(output)
    except json.JSONDecodeError:
        print_status("WARN", "Could not parse ECS service data")
        return

    for svc in data:
        name = svc.get("name", "?")
        status = svc.get("status", "?")
        desired = svc.get("desired", 0)
        running = svc.get("running", 0)
        rollout = svc.get("deployments") or "?"
        if status == "ACTIVE" and desired == running and desired > 0 and rollout == "COMPLETED":
            print_status("PASS", f"ECS service '{name}' is steady ({running}/{desired}, {rollout})")
        elif rollout == "IN_PROGRESS":
            print_status("WARN", f"ECS service '{name}' deployment in progress ({running}/{desired})")
        elif rollout == "FAILED":
            print_status("FAIL", f"ECS service '{name}' deployment FAILED ({running}/{desired})")
        else:
            print_status(
                "FAIL",
                f"ECS service '{name}' unhealthy: "
                f"status={status}, {running}/{desired}, rollout={rollout}",
            )


def check_ecs_target_group_health() -> None:
    """Verify ALB + NLB target groups for ECS services have all targets healthy.

    Hits both ``ecs-flip-api`` (ALB, HTTP 8000, target_type=ip) and
    ``ecs-fl-server-tcp`` (NLB, TCP 8002, target_type=ip). target_type=ip
    means each Fargate task ENI registers as a separate target.
    """
    print_status("INFO", "Checking ECS target group health (ALB + NLB)...")

    success, tgs = run_aws_command([
        "elbv2",
        "describe-target-groups",
        "--query",
        "TargetGroups[?starts_with(TargetGroupName, `ecs-`)].{name:TargetGroupName,arn:TargetGroupArn}",
        "--output",
        "json",
    ])
    if not success or not tgs:
        print_status("WARN", "Could not list ECS target groups")
        return

    try:
        tg_list = json.loads(tgs)
    except json.JSONDecodeError:
        print_status("WARN", "Could not parse target group data")
        return

    if not tg_list:
        print_status("WARN", "No ECS target groups found (expected ecs-flip-api and ecs-fl-server-tcp)")
        return

    for tg in tg_list:
        name = tg.get("name", "?")
        arn = tg.get("arn", "")
        if not arn:
            continue
        success2, health = run_aws_command([
            "elbv2",
            "describe-target-health",
            "--target-group-arn",
            arn,
            "--query",
            "TargetHealthDescriptions[].{id:Target.Id,state:TargetHealth.State,reason:TargetHealth.Reason}",
            "--output",
            "json",
        ])
        if not success2 or not health:
            print_status("WARN", f"Target group '{name}': could not query health")
            continue
        try:
            targets = json.loads(health)
        except json.JSONDecodeError:
            print_status("WARN", f"Target group '{name}': could not parse health")
            continue
        if not targets:
            print_status("FAIL", f"Target group '{name}' has no registered targets")
            continue
        unhealthy = [t for t in targets if t.get("state") != "healthy"]
        if not unhealthy:
            print_status("PASS", f"Target group '{name}' has {len(targets)} healthy target(s)")
        else:
            for t in unhealthy:
                print_status(
                    "FAIL",
                    f"Target group '{name}': target {t.get('id', '?')} is "
                    f"{t.get('state', '?')} ({t.get('reason', '')})",
                )


def check_ecs_log_streams(net_numbers: list[int]) -> None:
    """Verify ECS log groups have log streams written within the last hour.

    Stale log streams indicate a task that crashed and never restarted (or a
    misconfigured awslogs driver).
    """
    import time

    print_status("INFO", "Checking ECS log groups for recent activity...")
    log_groups = ["/ecs/flip-api"]
    for net in net_numbers:
        log_groups += [f"/ecs/fl-api-net-{net}", f"/ecs/fl-server-net-{net}"]
    threshold_ms = int((time.time() - 60 * 60) * 1000)

    for log_group in log_groups:
        success, output = run_aws_command([
            "logs",
            "describe-log-streams",
            "--log-group-name",
            log_group,
            "--order-by",
            "LastEventTime",
            "--descending",
            "--max-items",
            "1",
            "--query",
            "logStreams[0].lastEventTimestamp",
            "--output",
            "text",
        ])
        # ``--max-items 1`` adds a NextToken line ("None" or token) after the
        # value, so take just the first line.
        first_line = output.strip().split("\n", 1)[0] if output else ""
        if not first_line or first_line == "None":
            print_status("WARN", f"{log_group} has no log streams")
            continue
        try:
            last_ts = int(first_line)
        except ValueError:
            print_status("WARN", f"{log_group}: could not parse lastEventTimestamp ({first_line!r})")
            continue
        if last_ts >= threshold_ms:
            age_min = int((time.time() * 1000 - last_ts) / 60000)
            print_status("PASS", f"{log_group} active (last event {age_min} min ago)")
        else:
            age_min = int((time.time() * 1000 - last_ts) / 60000)
            print_status("WARN", f"{log_group} stale (last event {age_min} min ago)")


@click.command()
@click.option(
    "--terraform-dir",
    type=click.Path(exists=True, file_okay=False, path_type=Path),
    default=Path.cwd(),
    help="Directory containing terraform.tfstate",
)
@click.option(
    "--skip-network",
    is_flag=True,
    help="Skip network connectivity checks (ICMP, SSH)",
)
@click.option(
    "--skip-endpoints",
    is_flag=True,
    help="Skip HTTP endpoint checks",
)
@click.option(
    "--skip-docker",
    is_flag=True,
    help="Skip Docker container checks",
)
@click.option(
    "--skip-pipeline",
    is_flag=True,
    help="Skip trust pipeline health checks (task status, reimport, FL clients)",
)
@click.option(
    "--skip-deep",
    is_flag=True,
    help="Skip deep smoke tests (ECS, VPC endpoints, container errors, config checks)",
)
def main(
    terraform_dir: Path,
    skip_network: bool,
    skip_endpoints: bool,
    skip_docker: bool,
    skip_pipeline: bool,
    skip_deep: bool,
) -> None:
    """FLIP Deployment Status Checker.

    Verifies that the AWS deployment is functioning correctly.
    """
    # Change to terraform directory
    original_dir = Path.cwd()
    os.chdir(terraform_dir)

    # Determine ALB subdomain from environment. ALB_SUBDOMAIN takes precedence;
    # otherwise derive from PROD: 'true' → production domain, else → staging domain.
    _prod_env = os.getenv("PROD", "")
    _default_domain = "app.flip.aicentre.co.uk" if _prod_env == "true" else "stag.flip.aicentre.co.uk"
    alb_subdomain = os.getenv("ALB_SUBDOMAIN", _default_domain)

    # Check prerequisites
    print_section("Checking Prerequisites")

    if not check_command("terraform"):
        print_status("FAIL", "Required command 'terraform' not found. Please install it.")
        sys.exit(1)

    if not check_command("aws"):
        print_status("FAIL", "Required command 'aws' not found. Please install it.")
        sys.exit(1)

    if not check_command("ssh"):
        print_status("WARN", "ssh not found, remote checks will be skipped")

    if not check_command("jq"):
        print_status("WARN", "jq not found, JSON parsing will be limited")

    # Check terraform state
    print_section("Fetching Terraform Outputs")

    # Get Terraform outputs
    central_hub_id = get_terraform_output("Ec2InstanceId")

    trust_id = get_terraform_output("TrustEc2InstanceId")

    if not central_hub_id:
        print_status("FAIL", "Could not retrieve Central Hub SSM bastion instance ID from Terraform outputs")
        sys.exit(1)

    print_status("PASS", f"Central Hub SSM bastion ID: {central_hub_id}")

    if trust_id:
        print_status("PASS", f"Trust EC2 ID: {trust_id}")
    else:
        print_status("INFO", "Trust EC2 not found in outputs (may not be deployed)")

    # Check AWS resources
    print_section("Checking AWS Resources")

    # Check Central Hub EC2 instance status
    if central_hub_id:
        success, output = run_aws_command([
            "ec2",
            "describe-instances",
            "--instance-ids",
            central_hub_id,
            "--query",
            "Reservations[0].Instances[0].State.Name",
            "--output",
            "text",
        ])
        if success and output == "running":
            print_status("PASS", "Central Hub SSM bastion is running")
        else:
            print_status("FAIL", f"Central Hub SSM bastion state: {output}")

        success, ping_status = run_aws_command([
            "ssm",
            "describe-instance-information",
            "--filters",
            f"Key=InstanceIds,Values={central_hub_id}",
            "--query",
            "InstanceInformationList[0].PingStatus",
            "--output",
            "text",
        ])
        if success and ping_status == "Online":
            print_status("PASS", "Central Hub bastion is online in SSM")
        else:
            print_status("FAIL", f"Central Hub bastion SSM status: {format_ssm_ping_status(success, ping_status)}")

    # Check Trust EC2 instance status if it exists
    if trust_id:
        success, output = run_aws_command([
            "ec2",
            "describe-instances",
            "--instance-ids",
            trust_id,
            "--query",
            "Reservations[0].Instances[0].State.Name",
            "--output",
            "text",
        ])
        if success and output == "running":
            print_status("PASS", "Trust EC2 instance is running")
        else:
            print_status("FAIL", f"Trust EC2 instance state: {output}")

        # Check security groups
    if central_hub_id:
        success, sg_id = run_aws_command([
            "ec2",
            "describe-instances",
            "--instance-ids",
            central_hub_id,
            "--query",
            "Reservations[0].Instances[0].SecurityGroups[0].GroupId",
            "--output",
            "text",
        ])
        if success and sg_id:
            print_status("PASS", f"Security Group: {sg_id}")
            success, ingress_count = run_aws_command([
                "ec2",
                "describe-security-groups",
                "--group-ids",
                sg_id,
                "--query",
                "length(SecurityGroups[0].IpPermissions)",
                "--output",
                "text",
            ])
            if success and ingress_count == "0":
                print_status("PASS", "Central Hub bastion security group has no inbound rules")
            else:
                print_status("FAIL", f"Central Hub bastion security group inbound rule count: {ingress_count}")
        else:
            print_status("WARN", "Could not retrieve Security Group ID")

    # Check RDS instance
    print_status("INFO", "Checking RDS database...")
    success, rds_endpoint = run_aws_command([
        "rds",
        "describe-db-instances",
        "--query",
        "DBInstances[?contains(DBInstanceIdentifier, 'flip')].Endpoint.Address | [0]",
        "--output",
        "text",
    ])
    if success and rds_endpoint and rds_endpoint.strip():
        print_status("PASS", f"RDS endpoint found: {rds_endpoint.strip()}")

        success, rds_status = run_aws_command([
            "rds",
            "describe-db-instances",
            "--query",
            "DBInstances[?contains(DBInstanceIdentifier, 'flip')].DBInstanceStatus | [0]",
            "--output",
            "text",
        ])
        rds_status = (rds_status or "").strip()
        if success and rds_status == "available":
            print_status("PASS", "RDS instance is available")
        else:
            print_status("WARN", f"RDS instance status: {rds_status}")
    else:
        print_status("FAIL", "RDS endpoint not found")

    # Check FLIP application S3 buckets
    print_status("INFO", "Checking FLIP application S3 buckets...")
    for label, bucket_name in flip_application_bucket_names:
        if not bucket_name:
            print_status("WARN", f"{label} bucket env var not set in environment")
            continue
        success, _ = run_aws_command(["s3", "ls", f"s3://{bucket_name}"])
        if success:
            print_status("PASS", f"S3 bucket '{bucket_name}' ({label}) is accessible")
        else:
            # FAIL (not WARN): an inaccessible application bucket means the
            # flip-api data plane is broken (uploads, presigned downloads, FL
            # result retrieval all dead). WARN here would let the final exit
            # code stay 0 and let a CI/monitoring consumer report green.
            print_status(
                "FAIL",
                f"S3 bucket '{bucket_name}' ({label}) not accessible (may need different name or permissions)",
            )

    # Check Secrets Manager
    print_status("INFO", "Checking Secrets Manager...")
    success, secret_arn = run_aws_command([
        "secretsmanager",
        "list-secrets",
        "--query",
        "SecretList[?contains(Name, `FLIP_API`)].ARN",
        "--output",
        "text",
    ])
    if success and secret_arn:
        print_status("PASS", "Secrets Manager secret found")
    else:
        print_status("WARN", "Secrets Manager secret not found")

    # HTTPS/Certificate checks
    print_section("HTTPS & Certificate Status")

    # Get certificate ARN and domain from Terraform
    cert_arn = get_terraform_output("CertificateArn")

    if cert_arn:
        print_status("INFO", f"Checking ACM certificate: {cert_arn}")

        # Check certificate status
        success, cert_output = run_aws_command([
            "acm",
            "describe-certificate",
            "--certificate-arn",
            cert_arn,
            "--query",
            "Certificate.{Status:Status,DomainName:DomainName,ValidationStatus:DomainValidationOptions[0].ValidationStatus,FailureReason:FailureReason}",
            "--output",
            "json",
        ])

        if success:
            try:
                cert_data = json.loads(cert_output)
                status = cert_data.get("Status", "UNKNOWN")
                domain = cert_data.get("DomainName", "N/A")
                validation_status = cert_data.get("ValidationStatus", "N/A")
                failure_reason = cert_data.get("FailureReason", "")

                if status == "ISSUED":
                    print_status("PASS", f"Certificate for {domain} is ISSUED")
                elif status == "PENDING_VALIDATION":
                    print_status("WARN", f"Certificate is pending validation (Status: {validation_status})")
                elif status == "FAILED":
                    print_status("FAIL", f"Certificate failed: {failure_reason or 'Unknown reason'}")
                    if failure_reason == "CAA_ERROR":
                        print_status(
                            "INFO",
                            "CAA_ERROR: Domain has CAA records that block AWS ACM. "
                            "Contact domain admin to add 'amazon.com' to CAA records.",
                        )
                else:
                    print_status("WARN", f"Certificate status: {status}")
            except (json.JSONDecodeError, KeyError) as e:
                print_status("WARN", f"Could not parse certificate data: {e}")
        else:
            print_status("WARN", "Could not retrieve certificate status")

        # Check HTTPS endpoint connectivity
        https_url = f"https://{alb_subdomain}"
        print_status("INFO", f"Testing HTTPS connection to {https_url}...")

        import socket
        import ssl

        context = ssl.create_default_context()
        context.minimum_version = ssl.TLSVersion.TLSv1_2
        try:
            # Test SSL/TLS handshake
            with socket.create_connection((alb_subdomain, 443), timeout=10) as sock:
                with context.wrap_socket(sock, server_hostname=alb_subdomain) as ssock:
                    cert = ssock.getpeercert()
                    common_name = cert.get("subject", [[("commonName", "N/A")]])[0][0][1]
                    print_status(
                        "PASS",
                        f"HTTPS connection successful - Certificate issued to: {common_name}",
                    )

                    # Check certificate expiry
                    not_after = cert.get("notAfter", "")
                    if not_after:
                        print_status("INFO", f"Certificate expires: {not_after}")
        except ssl.SSLError as e:
            print_status("FAIL", f"SSL/TLS handshake failed: {e}")
        except socket.timeout:
            print_status("FAIL", f"Connection to {alb_subdomain}:443 timed out")
        except socket.gaierror:
            print_status("WARN", f"DNS resolution failed for {alb_subdomain} (may not be configured yet)")
        except ConnectionRefusedError:
            print_status("FAIL", f"Connection refused on port 443 for {alb_subdomain}")
        except Exception as e:
            print_status("WARN", f"HTTPS check failed: {e}")

        # Try HTTP request over HTTPS
        try:
            req = urllib.request.Request(https_url, method="HEAD")
            with urllib.request.urlopen(req, timeout=10, context=context) as response:
                print_status("PASS", f"HTTPS endpoint responding (HTTP {response.status})")
        except urllib.error.URLError as e:
            if hasattr(e, "reason") and "CERTIFICATE" in str(e.reason).upper():
                print_status("FAIL", f"Certificate validation failed: {e.reason}")
            else:
                print_status("INFO", f"HTTPS endpoint check: {e}")
        except Exception as e:
            print_status("INFO", f"HTTPS request failed (may not be deployed yet): {e}")
    else:
        print_status("INFO", "No ACM certificate found in Terraform outputs (HTTPS may not be configured)")

    # Network connectivity checks
    if not skip_network:
        print_section("Network Connectivity")

        # SSH connectivity check — Central Hub uses 'flip' SSH alias (SSM ProxyCommand)
        print_status("INFO", "Testing SSH connectivity to Central Hub (via SSM)...")
        success, _ = run_ssh_command(
            "",
            "flip",
            "echo 'SSH connection successful'",
            timeout=10,
        )
        if success:
            print_status("PASS", "SSH connection to Central Hub successful (via SSM)")
        else:
            print_status(
                "FAIL",
                "Cannot SSH to Central Hub via SSM (check SSM agent, IAM role, and SSH config)",
            )

        # Check Trust EC2 SSH connectivity (via SSM)
        if trust_id:
            print_status("INFO", "Testing SSH connectivity to Trust EC2 (via SSM)...")
            success, _ = run_ssh_command(
                "",
                "flip-trust",
                "echo 'SSH connection successful'",
                timeout=10,
            )
            if success:
                print_status("PASS", "SSH connection to Trust EC2 successful (via SSM)")
            else:
                print_status(
                    "WARN",
                    "Cannot SSH to Trust EC2 via SSM (check SSM agent, IAM role, and SSH config)",
                )

    # Parse NET_ENDPOINTS to determine which FL networks are configured (used by both endpoint and Docker checks)
    NET_ENDPOINTS = os.getenv("NET_ENDPOINTS", "{}")
    try:
        net_endpoints = json.loads(NET_ENDPOINTS.replace("'", '"'))
        configured_nets = list(net_endpoints.keys())
        configured_net_numbers = [int(net.split("-")[-1]) for net in configured_nets if net.startswith("net-")]
    except (json.JSONDecodeError, ValueError):
        configured_net_numbers = [1]  # Default to net-1 only

    # HTTP/HTTPS endpoint checks
    if not skip_endpoints:
        print_section("Application Endpoint Checks")

        # Public endpoints via CloudFront / ALB. flip-api now runs on ECS
        # Fargate behind the ALB, so the legacy EC2 ``http://localhost:8080``
        # check has been retired — the ALB endpoint is the source of truth.
        check_http_endpoint(f"https://{alb_subdomain}", "FLIP UI", 200)
        check_http_endpoint(f"https://{alb_subdomain}/api/health", "FLIP API Health (CloudFront → ALB)", 200)
        # FL API and FL server health: the per-net containers are ECS tasks
        # behind Cloud Map (fl-api-net-N.flip.local:8000) reachable only from
        # inside the VPC, so we cannot curl them from a developer workstation.
        # Their health is covered by check_ecs_services_running() (running
        # count + rollout state) and check_ecs_target_group_health() (NLB
        # ENI registration). The previous SSH+docker exec on the EC2 host
        # no longer applies — those containers do not run on EC2 anymore.

        # Trust EC2 endpoint checks
        if trust_id:
            # Trust EC2 is in a private subnet — check each service's HTTP endpoint
            # from inside the Trust EC2 itself via the 'flip-trust' SSH alias (SSM).
            # For browser access, operators use `make forward-trust` to tunnel these ports.
            print_status("INFO", "Checking Trust EC2 service endpoints (via SSM)...")
            # Use 127.0.0.1 instead of 'localhost' — Docker port publishing (including
            # Swarm ingress for XNAT) binds to 0.0.0.0 (IPv4); 'localhost' may resolve
            # to ::1 first on this host and hang the TCP connection.
            # Trust services use /health (always-on, exempt from internal-auth).
            # /docs is gated off in production builds, so it returned 404 here.
            # Grafana is part of the optional observability stack — treat its
            # absence as WARN, not FAIL.
            trust_endpoints = [
                ("XNAT", "http://127.0.0.1:8104/", ["200", "302"], "FAIL"),
                ("Orthanc", "http://127.0.0.1:8042/", ["200", "401"], "FAIL"),
                ("trust-api", "http://127.0.0.1:8020/health", ["200"], "FAIL"),
                ("imaging-api", "http://127.0.0.1:8001/health", ["200"], "FAIL"),
                ("data-access-api", "http://127.0.0.1:8010/health", ["200"], "FAIL"),
                ("Grafana", "http://127.0.0.1:3000/", ["200", "302"], "WARN"),
            ]
            for name, url, expected, severity in trust_endpoints:
                cmd = f"curl -s -o /dev/null -w '%{{http_code}}' --connect-timeout 10 --max-time 15 {url}"
                success, output = run_ssh_command("", "flip-trust", cmd, timeout=25)
                if not success:
                    print_status(severity, f"{name}: SSM/SSH transport failed — {output} — {url}")
                    continue
                code = output.strip()
                if code in expected:
                    print_status("PASS", f"{name} responding (HTTP {code}) — {url}")
                elif code == "000":
                    print_status(
                        severity,
                        f"{name}: connection refused / service not listening "
                        f"({severity}-level — `docker ps` on Trust EC2 if FAIL) — {url}",
                    )
                else:
                    print_status(
                        severity,
                        f"{name}: unexpected HTTP {code} (expected {expected}) — "
                        f"service responding but unhealthy — {url}",
                    )

            print_status(
                "INFO",
                "Trust API uses outbound polling. "
                "Verify by checking trust-api logs for successful hub polling and heartbeats.",
            )

        # Local (on-premises) Trust checks
        # In the outbound-only polling model, the local trust polls the hub —
        # we cannot verify connectivity from here. Direct the operator to check
        # trust-api logs for successful task polling and heartbeats.
        local_trust_ip = os.getenv("LOCAL_TRUST_IP")
        if local_trust_ip:
            print_section("Local Trust Checks")
            print_status(
                "INFO",
                f"Local trust at {local_trust_ip} uses outbound polling. "
                "Verify by checking trust-api logs for successful hub polling and heartbeats.",
            )
        else:
            print_status("INFO", "LOCAL_TRUST_IP not set — skipping local Trust checks")

    # Central Hub EC2 is now an SSM bastion only — flip-api, fl-api, and
    # fl-server all run as ECS Fargate tasks. We still check the bastion for
    # disk/memory headroom (SSM agent, PostgreSQL client, occasional ad-hoc
    # diagnostics), but the application-container checks moved to the ECS
    # section (check_ecs_services_running, check_ecs_target_group_health).
    if not skip_docker:
        success, _ = run_ssh_command("", "flip", "true", timeout=10)

        if success:
            print_section("Central Hub EC2 (SSM Bastion)")

            print_status("INFO", "Checking disk space...")
            success, disk_output = run_ssh_command(
                "",
                "flip",
                "df -h / | tail -1 | awk '{print $5}'",
            )
            if success and disk_output:
                disk_usage = int(disk_output.strip().rstrip("%"))
                if disk_usage < 80:
                    print_status("PASS", f"Bastion disk usage is {disk_usage}%")
                else:
                    print_status("WARN", f"Bastion disk usage is {disk_usage}% (consider cleanup if >80%)")

            print_status("INFO", "Checking memory usage...")
            success, mem_output = run_ssh_command(
                "",
                "flip",
                "free | grep Mem | awk '{printf(\"%.0f\", $3/$2 * 100)}'",
            )
            if success and mem_output:
                try:
                    mem_usage = int(mem_output.strip())
                    if mem_usage < 90:
                        print_status("PASS", f"Bastion memory usage is {mem_usage}%")
                    else:
                        print_status("WARN", f"Bastion memory usage is {mem_usage}% (high memory usage detected)")
                except ValueError:
                    print_status("WARN", "Could not parse bastion memory usage")
        else:
            print_status(
                "WARN",
                "Cannot SSH to Central Hub bastion via SSM. Application services run on ECS "
                "(checked separately) — bastion is only used for ad-hoc diagnostics. "
                "Verify SSM agent, IAM role, and SSH config if you need shell access.",
            )

        # Trust EC2 checks (via SSM)
        if trust_id:
            success, _ = run_ssh_command("", "flip-trust", "true", timeout=10)

            if success:
                print_section("Trust EC2 Status")
                print_status("PASS", "SSH connection to Trust EC2 successful")

                # Check Trust Docker containers
                print_status("INFO", "Checking Trust Docker containers...")
                success, trust_containers = run_ssh_command(
                    "",
                    "flip-trust",
                    "docker ps --format '{{.Names}}:{{.Status}}'",
                )

                if not success or not trust_containers:
                    print_status(
                        "WARN",
                        "Could not retrieve Trust container status (may not be deployed yet)",
                    )
                else:
                    # Count running containers
                    running_count = trust_containers.count("Up")
                    total_count = len(trust_containers.split("\n"))
                    print_status("INFO", f"Trust containers: {running_count}/{total_count} running")

                    # Check specific Trust API services
                    trust_services = ["trust-api", "imaging-api", "data-access-api"]
                    for service in trust_services:
                        service_found = False
                        for line in trust_containers.split("\n"):
                            if service in line and "Up" in line:
                                status = line.split(":", 1)[1] if ":" in line else ""
                                print_status(
                                    "PASS",
                                    f"Trust service '{service}' is running ({status})",
                                )
                                service_found = True
                                break
                        if not service_found:
                            print_status(
                                "WARN",
                                f"Trust service '{service}' not found or not running",
                            )

                    # Check FL clients on Trust EC2 (only for configured networks)
                    for net_num in configured_net_numbers:
                        client = f"fl-client-net-{net_num}"
                        client_found = False
                        for line in trust_containers.split("\n"):
                            if client in line and "Up" in line:
                                status = line.split(":", 1)[1] if ":" in line else ""
                                print_status("PASS", f"FL client '{client}' is running ({status})")
                                client_found = True
                                break
                        if not client_found:
                            print_status("WARN", f"FL client '{client}' not found or not running")

                    # Check OMOP database
                    if "omop-db" in trust_containers and "Up" in trust_containers:
                        for line in trust_containers.split("\n"):
                            if "omop-db" in line and "Up" in line:
                                status = line.split(":", 1)[1] if ":" in line else ""
                                print_status("PASS", f"OMOP database is running ({status})")
                                break
                    else:
                        print_status("WARN", "OMOP database not found or not running")

                # Check Docker networks on Trust EC2
                print_status("INFO", "Checking Trust Docker networks...")
                success, trust_networks = run_ssh_command(
                    "",
                    "flip-trust",
                    "docker network ls --format '{{.Name}}' 2>/dev/null",
                )

                expected_networks = [
                    "deploy_shared-net-1",
                    "deploy_shared-net-2",
                    "deploy_trust-network-1",
                ]
                if success:
                    for network in expected_networks:
                        if network in trust_networks:
                            print_status("PASS", f"Trust network '{network}' exists")
                        else:
                            print_status("WARN", f"Trust network '{network}' not found")

                # Check disk space on Trust EC2
                print_status("INFO", "Checking Trust EC2 disk space...")
                success, trust_disk_output = run_ssh_command(
                    "",
                    "flip-trust",
                    "df -h / | tail -1 | awk '{print $5}'",
                )
                if success and trust_disk_output:
                    trust_disk_usage = int(trust_disk_output.strip().rstrip("%"))
                    if trust_disk_usage < 80:
                        print_status("PASS", f"Trust disk usage is {trust_disk_usage}%")
                    else:
                        print_status(
                            "WARN",
                            (f"Trust disk usage is {trust_disk_usage}% (consider cleanup if >80%)"),
                        )

                # Check memory usage on Trust EC2
                print_status("INFO", "Checking Trust EC2 memory usage...")
                success, trust_mem_output = run_ssh_command(
                    "",
                    "flip-trust",
                    "free | grep Mem | awk '{printf(\"%.0f\", $3/$2 * 100)}'",
                )
                if success and trust_mem_output:
                    try:
                        trust_mem_usage = int(trust_mem_output.strip())
                        if trust_mem_usage < 90:
                            print_status("PASS", f"Trust memory usage is {trust_mem_usage}%")
                        else:
                            print_status(
                                "WARN",
                                (f"Trust memory usage is {trust_mem_usage}% (high memory usage detected)"),
                            )
                    except ValueError:
                        print_status("WARN", "Could not parse Trust memory usage")

                # Check for any exited containers on Trust EC2 (exclude Docker Swarm task history)
                success, trust_exited = run_ssh_command(
                    "",
                    "flip-trust",
                    "docker ps -a --filter 'status=exited' --format '{{.Names}}' 2>/dev/null"
                    " | grep -vE '\\.[0-9]+\\.[a-z0-9]{25}' || true",
                )
                if success and trust_exited:
                    print_status("WARN", f"Trust EC2 exited containers found: {trust_exited}")
            else:
                print_status("WARN", "Cannot SSH to Trust EC2 (check security groups and key)")

    # The Central Hub bastion deliberately has no CloudWatch agent. Application
    # logs are checked through the ECS log groups; only the Trust EC2 host-level
    # log group remains here.
    print_section("Trust EC2 CloudWatch Logs")

    if trust_id:
        print_status("INFO", "Checking Trust EC2 CloudWatch log groups...")
        trust_log_group = "/aws/ec2/flip-trust"
        success, output = run_aws_command([
            "logs",
            "describe-log-groups",
            "--log-group-name-prefix",
            trust_log_group,
        ])
        if success and trust_log_group in output:
            print_status("PASS", f"CloudWatch log group '{trust_log_group}' exists")

            # Check for recent log streams
            success, trust_streams_output = run_aws_command([
                "logs",
                "describe-log-streams",
                "--log-group-name",
                trust_log_group,
                "--order-by",
                "LastEventTime",
                "--descending",
                "--max-items",
                "1",
            ])
            if success:
                try:
                    trust_streams_data = json.loads(trust_streams_output)
                    if trust_streams_data.get("logStreams"):
                        print_status("PASS", "Recent Trust EC2 log streams found")
                    else:
                        print_status(
                            "WARN",
                            ("No recent Trust EC2 log streams (instance may not be sending logs yet)"),
                        )
                except json.JSONDecodeError:
                    print_status("WARN", "Could not parse Trust log streams data")
        else:
            print_status("WARN", "Trust EC2 CloudWatch log group not found")

    # Deep smoke tests (ECS, VPC, pipeline, config)
    if not skip_deep:
        print_section("Deep Smoke Tests")

        check_ecs_cluster()
        check_ecs_services_running(configured_net_numbers)
        check_ecs_target_group_health()
        check_vpc_endpoints()
        check_ecs_log_streams(configured_net_numbers)
        check_container_errors(configured_net_numbers)
        check_mfa_config()
        check_net_endpoints_consistency()

    # Trust pipeline health checks
    if not skip_pipeline:
        print_section("Trust Pipeline Health")

        check_trust_pipeline()
        check_xnat_health()
        check_reimport_status()
        check_fl_server_clients(configured_net_numbers)

    # Final summary
    print_section("Summary")

    click.echo()
    click.echo(f"{Colors.GREEN}Passed:   {counters.passed}/{counters.total}{Colors.NC}")
    click.echo(f"{Colors.RED}Failed:   {counters.failed}/{counters.total}{Colors.NC}")
    click.echo(f"{Colors.YELLOW}Warnings: {counters.warnings}/{counters.total}{Colors.NC}")
    click.echo()

    if counters.failed == 0:
        click.echo(f"{Colors.GREEN}✓ Deployment verification completed successfully!{Colors.NC}")
        if counters.warnings > 0:
            click.echo(
                f"{Colors.YELLOW}⚠ However, there are {counters.warnings} "
                f"warning(s) that should be reviewed.{Colors.NC}"
            )
            # Open centralhub on browser
            try:
                subprocess.run(["open", f"https://{alb_subdomain}"], check=False)
            except Exception:
                pass
        sys.exit(0)
    else:
        click.echo(f"{Colors.RED}✗ Deployment verification failed with {counters.failed} error(s).{Colors.NC}")
        click.echo(
            f"{Colors.YELLOW}Please review the failed checks and ensure all "
            f"services are properly configured.{Colors.NC}"
        )
        sys.exit(1)

    # Restore original directory
    os.chdir(original_dir)


if __name__ == "__main__":
    main()
