trustApi:
  env:
    CENTRAL_HUB_API_URL: "https://stag.flip.aicentre.co.uk/api"
trustName: "Azure node (HDRS test)"
flBackend: nvflare
flClient:
  kitHostPath: /opt/flip/fl-kit
  image:
    pin: sha-9fed4ed
omopDb:
  vocabLoad:
    s3Bucket: flipdev-aicentre
global:
  image:
    tag: stag
xnat:
  image:
    pin: 1390
