secrets:
  create: True
  data:
    aes-key-base64: VeLI33cXCVbM1AdR1j4bAIbY0nLbnMT5lPQxAiWyv3I=
    trust-internal-service-key-header: X-Trust-Internal-Service-Key
    omop-postgres-password: mypassword
    xnat-admin-password: "bH@BDC#Myl0lev6WQW#0u8GD"
    xnat-service-user: flipServiceAccount
    xnat-service-password: "bH@BDC#Myl0lev6WQW#0u8GD"
    grafana-admin-password: admin
