apiVersion: v1
kind: Secret
metadata:
  name: flip-trust-secrets
  namespace: flip-trust
type: Opaque
stringData:
  aes-key-base64: dGVzdC1hZXMta2V5LTEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNAo=
  trust-api-key: test-trust-key
  trust-internal-service-key-header: X-Trust-Internal-Service-Key
  trust-internal-service-key: test-trust-internal-key
  omop-postgres-password: test-omop-pass
  data-access-postgres-password: test-data-pass
  xnat-admin-password: test-xnat-admin
  xnat-service-user: test-xnat-svc
  xnat-service-password: test-xnat-svc-pass
  xnat-datasource-password: test-xnat-ds-pass
  grafana-admin-password: test-grafana-pass
  s3-access-key-id: test-s3-key
  s3-secret-access-key: test-s3-secret
