apiVersion: v1
kind: Secret
metadata:
  name: flip-trust-secrets
  namespace: flip-trust
type: Opaque
stringData:
  aes-key-base64: dGVzdC1hZXMta2V5LTEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNAo=  # pragma: allowlist secret
  trust-api-key: test-trust-key
  trust-internal-service-key-header: X-Trust-Internal-Service-Key
  trust-internal-service-key: test-trust-internal-key
  omop-postgres-password: test-omop-pass  # pragma: allowlist secret
  data-access-postgres-password: test-data-pass  # pragma: allowlist secret
  orthanc-registered-users: '{"ci": "ci-test-password"}'  # pragma: allowlist secret
  xnat-admin-password: test-xnat-admin  # pragma: allowlist secret
  xnat-service-user: test-xnat-svc
  xnat-service-password: test-xnat-svc-pass  # pragma: allowlist secret
  xnat-datasource-password: test-xnat-ds-pass  # pragma: allowlist secret
  xnat-datasource-admin-password: test-xnat-ds-admin-pass  # pragma: allowlist secret
  grafana-admin-password: test-grafana-pass  # pragma: allowlist secret
