#!/bin/bash
#
# Copyright (c) 2026 Guy's and St Thomas' NHS Foundation Trust & King's College London
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Fail fast (NVFLARE) when the per-net startup kits are missing, instead of letting
# fl-server crash-loop on "start.sh: No such file or directory". The kits live under
# FL_PROVISIONED_DIR and are generated by `make nvflare-provision-2-nets` — they are NOT
# created by `make up` (see fl_services/README.md). Net IDs come from NET_ENDPOINTS (same
# source as _ensure-fl-jobs-dir). Flower uses a different provisioned-certs path, so this
# check is NVFLARE-only.
#
# Inputs (passed as environment variables by the Makefile):
#   FL_BACKEND          nvflare | flower  (check is a no-op for anything but nvflare)
#   NET_ENDPOINTS       JSON object whose keys are the net IDs (e.g. {"net-1": "..."})
#   FL_PROVISIONED_DIR  workspace root containing <net>/services/fl-server-<net>/startup/

set -euo pipefail

FL_BACKEND="${FL_BACKEND:-nvflare}"
NET_ENDPOINTS="${NET_ENDPOINTS:-}"
FL_PROVISIONED_DIR="${FL_PROVISIONED_DIR:-deploy/workspace}"

# Flower (and any non-NVFLARE backend) provisions certs differently — nothing to check here.
if [ "${FL_BACKEND}" != "nvflare" ]; then
    exit 0
fi

# Empty *or* unparseable NET_ENDPOINTS both collapse to an empty `nets` (stderr from a
# bad parse is suppressed and `|| nets=""` keeps `set -e` from aborting first), so the
# guard below reports either case with one clear message.
nets=$(printf '%s' "${NET_ENDPOINTS}" | python3 -c "import json,sys; d=sys.stdin.read().strip(); print(' '.join(json.loads(d).keys()) if d else '')" 2>/dev/null) || nets=""
if [ -z "${nets}" ]; then
    echo "❌ check-fl-provisioned: NET_ENDPOINTS is empty or unparseable; cannot derive net IDs" >&2
    exit 1
fi

missing=""
for net in ${nets}; do
    [ -f "${FL_PROVISIONED_DIR}/${net}/services/fl-server-${net}/startup/start.sh" ] || missing="${missing} ${net}"
done

if [ -n "${missing}" ]; then
    echo "❌ NVFLARE workspace not provisioned for net(s):${missing}" >&2
    echo "   Startup kits are missing under ${FL_PROVISIONED_DIR}/<net>/services/ and are NOT created by 'make up'." >&2
    echo "   Provision first (from the repo root):" >&2
    echo "       make nvflare-provision-2-nets          # net-1 + net-2" >&2
    echo "       make nvflare-provision NET_NUMBER=<N>  # a single net" >&2
    echo "   See README 'Federated Learning Setup' / fl_services/README.md." >&2
    exit 1
fi
