#!/bin/bash
# Copyright (c) 2026 Guy's and St Thomas' NHS Foundation Trust & King's College London
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Register each deploy trust (TRUST_1_*, TRUST_2_*, ...) on the hub and
# distribute its kit file. Per trust:
#   1. Run `flip_api.scripts.register_trust --name <name> [--code] [--region]`
#      as a one-off ECS task against the running flip-api task definition.
#      register_trust is idempotent — an already-registered trust emits [].
#   2. Read the kit JSON from the task's CloudWatch log stream.
#   3. Route the kit by TRUST_<n>_HOST: "ec2" → scp to the trust EC2 via the
#      SSM-backed `flip-trust` ssh alias; "local" → write trust/.env.<slot>.
# Re-runs are no-ops (no kit emitted → nothing distributed).

set -eo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../../.." && pwd)"
# shellcheck disable=SC1091
source "$SCRIPT_DIR/utils.sh"

check_aws_profile

: "${ECS_CLUSTER:=flip-cluster}"
ECS_SERVICE="${ECS_SERVICE:-flip-api}"
TASK_FAMILY="${TASK_FAMILY:-flip-api}"
LOG_GROUP="${LOG_GROUP:-/ecs/flip-api}"

# How many TRUST_<n>_* slots to consider.
TRUST_SLOT_COUNT="${TRUST_SLOT_COUNT:-2}"

log_info "Discovering live $ECS_SERVICE service network config..."
SVC_JSON="$(aws_cmd ecs describe-services --cluster "$ECS_CLUSTER" --services "$ECS_SERVICE" --query 'services[0]')"
SUBNETS="$(echo "$SVC_JSON" | jq -r '.networkConfiguration.awsvpcConfiguration.subnets | join(",")')"
SGS="$(echo "$SVC_JSON" | jq -r '.networkConfiguration.awsvpcConfiguration.securityGroups | join(",")')"
ASSIGN_PUB="$(echo "$SVC_JSON" | jq -r '.networkConfiguration.awsvpcConfiguration.assignPublicIp')"
if [ -z "$SUBNETS" ] || [ -z "$SGS" ]; then
    log_error "Could not read network config from $ECS_SERVICE service. Is it deployed?"
    exit 1
fi

# Wait for the service to be stable — its task entrypoint seeds the DB (incl. the
# FL kit-slot pool register_trust claims from); stable means that seed completed.
log_info "Waiting for the $ECS_SERVICE service to reach a stable state..."
aws_cmd ecs wait services-stable --cluster "$ECS_CLUSTER" --services "$ECS_SERVICE"
log_success "$ECS_SERVICE service is stable."

write_kit_file() {
    local path="$1" kit="$2"
    {
        echo "# Generated by register-trusts.sh on $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
        echo "# Plaintext credentials — keep this file secret. Never commit it."
        echo "TRUST_API_KEY=$(echo "$kit" | jq -r '.trust_api_key')"
        echo "TRUST_INTERNAL_SERVICE_KEY=$(echo "$kit" | jq -r '.trust_internal_service_key')"
        echo "FL_KIT_SLOT=$(echo "$kit" | jq -r '.fl_kit_slot')"
        echo "FL_KIT_SLOT_NUMBER=$(echo "$kit" | jq -r '.fl_kit_slot_number')"
        echo "EXPECTED_TRUST_ID=$(echo "$kit" | jq -r '.trust_id')"
    } > "$path"
    chmod 600 "$path"
}

# Register one trust (by TRUST_<idx>_* env vars) via a one-off ECS task.
register_one() {
    local idx="$1"
    local nv cv rv hv name code region host
    nv="TRUST_${idx}_NAME"; cv="TRUST_${idx}_CODE"; rv="TRUST_${idx}_REGION"; hv="TRUST_${idx}_HOST"
    name="${!nv:-}"; code="${!cv:-}"; region="${!rv:-}"; host="${!hv:-}"
    if [ -z "$name" ]; then
        log_info "TRUST_${idx}_NAME unset — skipping slot $idx."
        return 0
    fi

    log_info "Registering trust $idx ('$name') via a one-off ECS task..."
    local cmd_args
    cmd_args=(uv run python -m flip_api.scripts.register_trust --name "$name")
    [ -n "$code" ] && cmd_args+=(--code "$code")
    [ -n "$region" ] && cmd_args+=(--region "$region")
    local overrides
    # `--args -- ` is required: cmd_args contains dash-prefixed values (`-m`, `--name`, ...)
    # and jq scans the whole argv for options regardless of `--args`. The `--` end-of-options
    # marker is what makes jq treat the rest as positional. Holds on jq 1.6 and 1.7+.
    overrides="$(jq -n '{containerOverrides:[{name:"flip-api",command:$ARGS.positional}]}' --args -- "${cmd_args[@]}")"

    local task_arn task_id
    task_arn="$(aws_cmd ecs run-task \
        --cluster "$ECS_CLUSTER" --task-definition "$TASK_FAMILY" --launch-type FARGATE \
        --started-by "register-trusts" \
        --network-configuration "awsvpcConfiguration={subnets=[${SUBNETS}],securityGroups=[${SGS}],assignPublicIp=${ASSIGN_PUB}}" \
        --overrides "$overrides" --query 'tasks[0].taskArn' --output text)"
    task_id="${task_arn##*/}"
    aws_cmd ecs wait tasks-stopped --cluster "$ECS_CLUSTER" --tasks "$task_id"

    local log_events kit
    log_events="$(aws_cmd logs get-log-events --log-group-name "$LOG_GROUP" \
        --log-stream-name "flip-api/flip-api/$task_id" --start-from-head \
        --query 'events[].message' --output text)"
    # register_trust prints one JSON array on stdout — the last line starting with '['.
    # `aws ... --output text` joins the events[] list with TABs, so the kit message
    # arrives TAB-prefixed; split on TAB and trim before matching the leading '['.
    kit="$(echo "$log_events" | tr '\t' '\n' | sed 's/^[[:space:]]*//' | awk 'NF' | grep -E '^\[' | tail -n 1 || true)"
    if [ -z "$kit" ] || [ "$(echo "$kit" | jq 'length')" = "0" ]; then
        log_success "Trust '$name' already registered (or no kit emitted) — nothing to distribute."
        return 0
    fi
    kit="$(echo "$kit" | jq -c '.[0]')"

    local slot
    slot="$(echo "$kit" | jq -r '.fl_kit_slot')"
    case "$host" in
        local)
            write_kit_file "$REPO_ROOT/trust/.env.${slot}" "$kit"
            log_success "Wrote kit for '$name' → trust/.env.${slot}"
            ;;
        ec2)
            local tmp_kit
            tmp_kit="$(mktemp)"
            write_kit_file "$tmp_kit" "$kit"
            scp -q "$tmp_kit" "flip-trust:/opt/flip/trust/.env.${slot}"
            rm -f "$tmp_kit"
            log_success "Distributed kit for '$name' to the trust EC2 (.env.${slot})."
            ;;
        *)
            log_warn "TRUST_${idx}_HOST='$host' unknown for trust '$name'; kit not distributed:"
            echo "$kit" >&2
            ;;
    esac
}

for idx in $(seq 1 "$TRUST_SLOT_COUNT"); do
    register_one "$idx"
done

log_success "register-trusts complete."
