# Copyright (c) 2026 Guy's and St Thomas' NHS Foundation Trust & King's College London
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

"""baseline schema

Revision ID: 75c871e682a4
Revises: 
Create Date: 2026-06-02 16:22:10.342553

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '75c871e682a4'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fl_nets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint'),
    sa.UniqueConstraint('name')
    )
    op.create_table('permission',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('permission_name', sa.String(), nullable=False),
    sa.Column('permission_description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('creation_timestamp', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('UNSTAGED', 'STAGED', 'APPROVED', name='projectstatus'), nullable=False),
    sa.Column('dicom_to_nifti', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('site_banner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site_config',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_site_config_key'), 'site_config', ['key'], unique=False)
    op.create_table('trust',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('api_key_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trusts_audit',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trust_id', sa.Uuid(), nullable=False),
    sa.Column('trust_name', sa.String(), nullable=False),
    sa.Column('action', sa.Enum('REGISTERED', 'DELETED', name='trustauditaction'), nullable=False),
    sa.Column('modified_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('audit_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trusts_audit_trust_id'), 'trusts_audit', ['trust_id'], unique=False)
    op.create_table('user_profile',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('organisation', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('users_audit',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('modified_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fl_kit_slot',
    sa.Column('slot_name', sa.String(), nullable=False),
    sa.Column('slot_number', sa.Integer(), nullable=False),
    sa.Column('assigned_to_trust_id', sa.Uuid(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_trust_id'], ['trust.id'], ),
    sa.PrimaryKeyConstraint('slot_name')
    )
    op.create_index(op.f('ix_fl_kit_slot_assigned_to_trust_id'), 'fl_kit_slot', ['assigned_to_trust_id'], unique=False)
    op.create_table('model',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ERROR', 'STOPPED', 'PENDING', 'INITIATED', 'PREPARED', 'TRAINING_STARTED', 'RESULTS_UPLOADED', name='modelstatus'), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('creation_timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_trust_intersect',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('trust_id', sa.Uuid(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['trust_id'], ['trust.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_trust_intersect_project_id'), 'project_trust_intersect', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_trust_intersect_trust_id'), 'project_trust_intersect', ['trust_id'], unique=False)
    op.create_table('project_user_access',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects_audit',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.Enum('DELETE', 'EDIT', 'APPROVE', 'STAGE', 'UNSTAGE', name='projectauditaction'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('audit_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_audit_project_id'), 'projects_audit', ['project_id'], unique=False)
    op.create_table('queries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('queried_trust_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queries_created_by'), 'queries', ['created_by'], unique=False)
    op.create_index(op.f('ix_queries_project_id'), 'queries', ['project_id'], unique=False)
    op.create_table('role_permission',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trust_task',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trust_id', sa.Uuid(), nullable=False),
    sa.Column('task_type', sa.Enum('COHORT_QUERY', 'CREATE_IMAGING', 'DELETE_IMAGING', 'GET_IMAGING_STATUS', 'REIMPORT_STUDIES', 'UPDATE_USER_PROFILE', name='tasktype'), nullable=False),
    sa.Column('payload', sa.String(), nullable=False),
    sa.Column('query_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED', name='taskstatus'), nullable=False),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('needs_post_processing', sa.Boolean(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trust_id'], ['trust.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trust_task_query_id'), 'trust_task', ['query_id'], unique=False)
    op.create_index(op.f('ix_trust_task_trust_id'), 'trust_task', ['trust_id'], unique=False)
    op.create_table('user_role',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('xnat_project_status',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('xnat_project_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('trust_id', sa.Uuid(), nullable=True),
    sa.Column('retrieve_image_status', sa.Enum('RETRIEVE_STARTED', 'RETRIEVE_COMPLETED', 'RETRIEVE_IN_PROGRESS', 'RETRIEVE_ERROR', 'CREATED', 'DELETED', name='xnatimagestatus'), nullable=False),
    sa.Column('query_at_creation', sa.Uuid(), nullable=True),
    sa.Column('last_reimport', sa.DateTime(), nullable=False),
    sa.Column('reimport_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['trust_id'], ['trust.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fl_job',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('model_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'IN_PROGRESS', 'COMPLETED', 'DELETED', name='jobstatus'), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('started', sa.DateTime(), nullable=True),
    sa.Column('completed', sa.DateTime(), nullable=True),
    sa.Column('fl_backend_job_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fl_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('model_id', sa.Uuid(), nullable=False),
    sa.Column('log_date', sa.DateTime(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('trust', sa.Uuid(), nullable=True),
    sa.Column('fl_client_name', sa.String(), nullable=True),
    sa.Column('log', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], ),
    sa.ForeignKeyConstraint(['trust'], ['trust.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fl_metrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trust', sa.Uuid(), nullable=False),
    sa.Column('fl_client_name', sa.String(), nullable=False),
    sa.Column('model_id', sa.Uuid(), nullable=False),
    sa.Column('global_round', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('result', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], ),
    sa.ForeignKeyConstraint(['trust'], ['trust.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_trust_intersect',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'REQUEST_SENT', 'INITIALISED', name='trustintersectstatus'), nullable=False),
    sa.Column('model_id', sa.Uuid(), nullable=True),
    sa.Column('trust_id', sa.Uuid(), nullable=True),
    sa.Column('fl_client_endpoint', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], ),
    sa.ForeignKeyConstraint(['trust_id'], ['trust.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('models_audit',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('model_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.Enum('DELETE', 'EDIT', 'PREPARED', 'TRAINING_STARTED', 'RESULTS_UPLOADED', name='modelauditaction'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('audit_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_models_audit_model_id'), 'models_audit', ['model_id'], unique=False)
    op.create_table('query_result',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('query_id', sa.Uuid(), nullable=False),
    sa.Column('trust_id', sa.Uuid(), nullable=True),
    sa.Column('data', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ),
    sa.ForeignKeyConstraint(['trust_id'], ['trust.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('query_stats',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('stats', sa.String(), nullable=False),
    sa.Column('stats_received', sa.DateTime(), nullable=False),
    sa.Column('query_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uploaded_files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('SCANNING', 'COMPLETED', 'ERROR', name='fileuploadstatus'), nullable=False),
    sa.Column('size', sa.Float(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('tag', sa.String(), nullable=True),
    sa.Column('model_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fl_job_trust',
    sa.Column('fl_job_id', sa.Uuid(), nullable=False),
    sa.Column('trust_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['fl_job_id'], ['fl_job.id'], ),
    sa.ForeignKeyConstraint(['trust_id'], ['trust.id'], ),
    sa.PrimaryKeyConstraint('fl_job_id', 'trust_id')
    )
    op.create_table('fl_scheduler',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('net_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'BUSY', name='netstatus'), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['fl_job.id'], ),
    sa.ForeignKeyConstraint(['net_id'], ['fl_nets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fl_scheduler')
    op.drop_table('fl_job_trust')
    op.drop_table('uploaded_files')
    op.drop_table('query_stats')
    op.drop_table('query_result')
    op.drop_index(op.f('ix_models_audit_model_id'), table_name='models_audit')
    op.drop_table('models_audit')
    op.drop_table('model_trust_intersect')
    op.drop_table('fl_metrics')
    op.drop_table('fl_logs')
    op.drop_table('fl_job')
    op.drop_table('xnat_project_status')
    op.drop_table('user_role')
    op.drop_index(op.f('ix_trust_task_trust_id'), table_name='trust_task')
    op.drop_index(op.f('ix_trust_task_query_id'), table_name='trust_task')
    op.drop_table('trust_task')
    op.drop_table('role_permission')
    op.drop_index(op.f('ix_queries_project_id'), table_name='queries')
    op.drop_index(op.f('ix_queries_created_by'), table_name='queries')
    op.drop_table('queries')
    op.drop_index(op.f('ix_projects_audit_project_id'), table_name='projects_audit')
    op.drop_table('projects_audit')
    op.drop_table('project_user_access')
    op.drop_index(op.f('ix_project_trust_intersect_trust_id'), table_name='project_trust_intersect')
    op.drop_index(op.f('ix_project_trust_intersect_project_id'), table_name='project_trust_intersect')
    op.drop_table('project_trust_intersect')
    op.drop_table('model')
    op.drop_index(op.f('ix_fl_kit_slot_assigned_to_trust_id'), table_name='fl_kit_slot')
    op.drop_table('fl_kit_slot')
    op.drop_table('users_audit')
    op.drop_table('user_profile')
    op.drop_index(op.f('ix_trusts_audit_trust_id'), table_name='trusts_audit')
    op.drop_table('trusts_audit')
    op.drop_table('trust')
    op.drop_index(op.f('ix_site_config_key'), table_name='site_config')
    op.drop_table('site_config')
    op.drop_table('site_banner')
    op.drop_table('roles')
    op.drop_table('projects')
    op.drop_table('permission')
    op.drop_table('fl_nets')
    # ### end Alembic commands ###

    # Hand-added: drop the native PostgreSQL ENUM types. `op.create_table` with a
    # `sa.Enum(name=...)` column auto-creates the type on upgrade, but `op.drop_table`
    # does NOT drop it — autogenerate never emits these. Without the explicit drops a
    # `downgrade base` leaves the types orphaned and the next `upgrade head` fails with
    # "type ... already exists". `IF EXISTS` keeps the downgrade idempotent.
    for enum_name in (
        "projectstatus",
        "modelstatus",
        "jobstatus",
        "netstatus",
        "trustintersectstatus",
        "taskstatus",
        "tasktype",
        "xnatimagestatus",
        "fileuploadstatus",
        "modelauditaction",
        "projectauditaction",
        "trustauditaction",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
